/*---------------------------------------------------------------------------------------------
 *  Copyright (c) 2026 Kaedyn Limon. All rights reserved.
 *  Licensed under the MIT License. See LICENSE in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// BunManager — Async bridge for Bun subprocess communication.
// Manages services (query/push), web component registration, and action dispatch.
// Process lifecycle owned by ApplicationRuntime.
// Protocol handling delegated to ManagedProcessBridge.

using System.Collections.Concurrent;
using System.Text.Json;
using Keystone.Core.Management.Process;
using Keystone.Core.Management.Protocol;
using Keystone.Core.Plugins;

namespace Keystone.Core.Management.Bun;

public class BunManager : IBunService
{
    private static BunManager? _instance;
    public static BunManager Instance => _instance ??= new BunManager();

    private ManagedProcessBridge? _bridge;

    private volatile List<string> _services = new();
    private volatile List<string> _webComponents = new();
    private int _bunPort;

    private readonly ConcurrentDictionary<string, Func<JsonElement?, Task<object?>>> _hostHandlers = new();

    /// <summary>Called when a service pushes data to C# via ctx.push(channel, data).</summary>
    public Action<string, string>? OnServicePush { get; set; }

    /// <summary>Called when a web component dispatches an action back to C#.</summary>
    public Action<string>? OnWebAction { get; set; }

    /// <summary>Fired when Bun hot-reloads a web component. Arg is the component name.</summary>
    public Action<string>? OnWebComponentHmr { get; set; }

    public bool IsRunning => _bridge is { IsReady: true } && _bridge.Process.IsRunning;
    public IReadOnlyList<string> Services => _services;
    public IReadOnlyList<string> WebComponents => _webComponents;
    public int BunPort => _bunPort;

    /// <summary>Per-launch session token for WS authentication. Generated by ProcessSupervisor.</summary>
    public string? SessionToken { get; set; }

    public int NextId() => _bridge?.NextId() ?? 0;

    // ── Attach / Detach ────────────────────────────────────────────────

    public bool TryAttachFromReadySignal(BunProcess process, string jsonLine)
    {
        try
        {
            using var doc = JsonDocument.Parse(jsonLine);
            var root = doc.RootElement;
            if (!root.TryGetProperty("status", out var status) || status.GetString() != "ready")
                return false;

            var services = root.TryGetProperty("services", out var sv)
                ? sv.EnumerateArray().Select(e => e.GetString()!).ToList()
                : new List<string>();
            var webComponents = root.TryGetProperty("webComponents", out var wc)
                ? wc.EnumerateArray().Select(e => e.GetString()!).ToList()
                : new List<string>();
            var port = root.TryGetProperty("port", out var p) ? p.GetInt32() : 0;

            Attach(process, services, webComponents, port);
            Console.WriteLine($"[BunManager] Attached: {services.Count} services, {webComponents.Count} web, port={port}");
            return true;
        }
        catch { return false; }
    }

    public void Attach(BunProcess process, List<string> services,
        List<string>? webComponents = null, int port = 0)
    {
        _bridge?.Detach();
        _bridge = new ManagedProcessBridge(process);
        _bridge.OnServicePush = (ch, d) => OnServicePush?.Invoke(ch, d);
        _bridge.OnWebAction = a => OnWebAction?.Invoke(a);
        _bridge.OnHmr = c => OnWebComponentHmr?.Invoke(c);
        _bridge.OnHostQuery = DispatchHostQuery;

        _services = services;
        _webComponents = webComponents ?? new();
        _bunPort = port;

        _bridge.MarkReady();
    }

    public void Detach()
    {
        _bridge?.Detach();
        _bridge = null;
        _services = new();
        _webComponents = new();
        _bunPort = 0;
    }

    // ── Send ──────────────────────────────────────────────────────────────

    public void Send(string jsonLine) => _bridge?.Send(jsonLine);

    public void Send(int id, string jsonLine, Action<string> onResponse)
        => _bridge?.Send(id, jsonLine, onResponse);

    public void HandleAction(string action) => _bridge?.HandleAction(action);

    public void Push(string channel, object data) => _bridge?.Push(channel, data);

    public string? WebComponentUrl(string name)
    {
        if (_webComponents.Contains(name))
            return $"http://127.0.0.1:{_bunPort}/{name}";
        return null;
    }

    public Task<string?> Query(string service, object? args = null)
        => _bridge?.Query(service, args) ?? Task.FromResult<string?>(null);

    public Task<string?> Eval(string code)
        => _bridge?.Eval(code) ?? Task.FromResult<string?>(null);

    // ── Host query handlers (Bun→C# calls) ──────────────────────────────

    /// <summary>Register a handler that Bun services can call via ipc.host.call(name, args).</summary>
    public void RegisterHostHandler(string name, Func<JsonElement?, Task<object?>> handler)
    {
        _hostHandlers[name] = handler;
    }

    /// <summary>Remove a host query handler.</summary>
    public void RemoveHostHandler(string name)
    {
        _hostHandlers.TryRemove(name, out _);
    }

    internal async Task<object?> DispatchHostQuery(string service, string? argsJson)
    {
        if (!_hostHandlers.TryGetValue(service, out var handler))
            throw new InvalidOperationException($"No host handler: {service}");

        JsonElement? args = null;
        if (argsJson != null)
        {
            using var doc = JsonDocument.Parse(argsJson);
            args = doc.RootElement.Clone();
        }

        return await handler(args);
    }

    // ── Binary socket (stream/binary lane) ────────────────────────────

    /// <summary>The binary socket server for stream/binary IPC. Set by ApplicationRuntime.</summary>
    public BinarySocketServer? BinarySocket { get; set; }

    /// <summary>Called when an envelope arrives on the binary socket from Bun.</summary>
    public void HandleBinaryEnvelope(KeystoneEnvelope envelope)
    {
        OnBinaryEnvelope?.Invoke(envelope);
    }

    /// <summary>Subscribe to binary envelopes from Bun (stream_open, stream_chunk, stream_close, etc.).</summary>
    public Action<KeystoneEnvelope>? OnBinaryEnvelope { get; set; }

    /// <summary>Send an envelope to Bun over the binary socket.</summary>
    public void SendEnvelope(KeystoneEnvelope envelope)
    {
        BinarySocket?.SendEnvelope(envelope);
    }

    public void Shutdown() => Detach();
}
